name: polymaker
author: Yusril Rapsanjani<yuranicorp@gmail.com>
version: 0.0.2+1
homepage: https://github.com/yusriltakeuchi/polymaker.git
description: Polymaker is a flutter package to make it easier to map polygon locations in Google Maps, because the appearance is realtime when in Edit Mode, so we know the exact position without guessing through the backend system.
environment: 
  sdk: '>=2.2.0 <3.0.0'
dependencies: 
  google_maps_flutter: ^0.5.27+3
  location: ^3.0.2
  provider: ^4.1.2
  simple_animations: ^1.3.3
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - images/
    - assets/map_style.txt
